#:kivy 1.11.0
#:import SlideTransition kivy.uix.screenmanager.SlideTransition

<ScreenManagement>:
    transition: SlideTransition(direction='left')
    StationTest:

<StationTest>:
    name: 'StationTest'
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1, 0.35
        padding: 0, -200, 0, 0
        MyButton:
        MyButton:
        MyButton:
        MyButton:



<MyButton@Button>:
    text: "conten  # black color textts (%s)"%(app.abcd)

    background_color: (1, 1, 1, 1)  
    color: 0, 0, 0, 1  